<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="MAIN" Id="{6dd4f5eb-60fa-4e7b-ab23-f07ecac8c1c3}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	a:INT;
	b:INT;
	c:INT;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
c:=a+b;

]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="10" Count="0" />
      <LineId Id="2" Count="0" />
      <LineId Id="13" Count="0" />
      <LineId Id="12" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>